### ISSUE TITLE
Should have a way to exclude subroutes with patterns

### ISSUE THREAD

**Issue by evidanary** [eigenbart/rack-jwt#4]
Currently we can exclude routes of type "/static" but not of type "/static/javascript/build.js"

There should be a way to exclude all sub routes. This can be achieved by changing
https://github.com/eigenbart/rack-jwt/blob/master/lib/rack/jwt/auth.rb#L15
to call a function that can do starts_with?

If that looks OK, I can go ahead and send a PR.

**Comment by jturkel** [comment]
I would love to see this feature too!

**Comment by grempe** [comment]
This can be closed I think as this functionality was included in the commits you just merged from me and included in the new release.

https://github.com/eigenbart/rack-jwt/commit/79accab1db2a9aeb3b798c49084f324dab7587fd
