### ISSUE TITLE
Customize error messages from Auth

### ISSUE THREAD

**Issue by Morred** [eigenbart/rack-jwt#9]
Hi there,

First of all, thanks for writing this gem, it's super useful!

I guess this one is more like a feature request, I'm looking for a way to customize the format of the error responses of the Auth class.

Every time something fails, it will automatically return a 401 response with the error body format that is hardcoded into this method, so currently I'm just monkeypatching the return_error method to build the error body into the format I need.

Is a general, more flexible way to format the error responses something you would consider adding to this gem?

**Comment by eigenbart** [comment]
Hi @Morred I'm not longer maintaining that gem. You can find the new repo here https://github.com/eparreno/rack-jwt

Your issue has been moved there
